apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cicd-demo-pipeline
spec:
  params:
    # clone from which repo and revision
    - name: repo_url
      type: string
    - name: repo_revision
      type: string
    - name: git_branch
      type: string
    # push image to which registry and repository
    - name: image-registry
      default: docker.io/sunway
    - name: image-repo-name
      type: string
  workspaces:
    - name: git-source
    - name: docker-cred
    - name: github-cred
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: repo_url
          value: $(params.repo_url)
        - name: revision
          value: $(params.repo_revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: git-source
        - name: ssh-directory
          workspace: github-cred
    - name: build-image
      runAfter: [ fetch-from-git ]
      taskRef:
        name: kaniko-build-and-push
      params:
        - name: IMAGE
          value: $(params.image-registry)/$(params.image-repo-name):$(tasks.fetch-from-git.results.commit)
        - name: CONTEXT
          value: ""
        - name: DOCKERFILE
          value: $(workspaces.source.path)/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
        - name: dockerconfig
          workspace: docker-cred
    - name: update-image-tag
      runAfter: [ build-image ]
      taskRef:
        name: update-image-tag
      params:
        - name: git_branch
          value: $(params.git_branch)
        - name: commit_id
          value: $(tasks.fetch-from-git.results.commit)
        # cd https://github.com/sunway910/cicd-demo/$project_path
        - name: project_path
          value: cicd-demo-helm
      workspaces:
        - name: source
          workspace: git-source
        - name: ssh-directory
          workspace: github-cred
  # delete finally task if you dont need to send notification to IM
  # finally task will not be executed if pipeline_start_time/pipeline_end_time is null
  finally:
    - name: send-notification-to-lark
      taskRef:
        name: send-notification-to-lark
      params:
        - name: webhook_url
          value: "https://open.larksuite.com/open-apis/bot/v2/hook/xxxxx"
        - name: pipeline_title
          value: "Demo Pipeline"
        - name: pipeline_result
          value: $(tasks.status)
        - name: commit_info
          value: $(tasks.fetch-from-git.results.commit-info)
        - name: pipeline_result_link
          value: "https://tekton-dashboard.sunway.run/#/pipelineruns"
        - name: github_commit_link
          value: https://github.com/sunway910/cicd-demo/commit/$(tasks.fetch-from-git.results.commit)
        - name: mention_user_open_id
          value: "all"
        - name: pipeline_start_time
          value: $(tasks.fetch-from-git.results.pipeline-start-time)
        - name: pipeline_end_time
          value: $(tasks.update-image-tag.results.pipeline-end-time)
