apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.label }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.service.label }}
  ports:
    - protocol: TCP
      name: {{ .Values.service.label }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}